# Generated by Django 2.0.6 on 2019-08-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_writer',
            field=models.CharField(max_length=256),
        ),
    ]
