# Generated by Django 2.0.6 on 2019-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuser',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blogsuser',
            name='is_delete',
            field=models.IntegerField(default=1),
        ),
    ]
